---

- fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: 
    - logstash_filter_conf
    - logstash_input_conf
    - logstash_output_conf
    - logstash_log_dir
    - logstash_user
    - logstash_etc_dir
