---
# here comes the real playbook, executed after env check


- name: allow java to open privilegied socket (1)
  capabilities: path="/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" capability=cap_net_bind_service=+epi state=present
  notify: restart_logstash

- name: Add GPG key
  apt_key: url={{logstash_repo_gpg_key}} state=present

- name: Install Logstash apt_repository
  apt_repository: repo="deb {{ logstash_apt_repo }} stable main" state=present

- name: Install Logstash
  apt: pkg=logstash state=present cache_valid_time=3600 update_cache=yes

- name: Conf logstashInput
  template: src=logstash_input.conf.j2 dest="{{logstash_etc_dir}}/logstash_input.conf"
  notify: restart_logstash
  
- name: Conf logstashOutput
  template: src=logstash_output.conf.j2 dest="{{logstash_etc_dir}}/logstash_output.conf"
  notify: restart_logstash

- name: Conf logstashFilter
  template: src=logstash_filter.conf.j2 dest="{{logstash_etc_dir}}/logstash_filter.conf"
  notify: restart_logstash

- name: List installed plugins
  command: /opt/logstash/bin/logstash-plugin list
  register: list
  changed_when: 1 == 2

- name: Install configured plugins.
  command: /opt/logstash/bin/logstash-plugin install {{ item }}
  with_items: "{{ logstash_plugins }}"
  when: "item not in list.stdout"
  notify: restart_logstash