---
# here comes the real playbook, executed after env check


- name: Add GPG key
  apt_key: url={{logstash_repo_gpg_key}} state=present

- name: Install Logstash apt_repository
  apt_repository: repo="deb {{ logstash_apt_repo }} stable main" state=present

- name: Install Logstash
  apt: pkg=logstash state=present cache_valid_time=3600 update_cache=yes

- name: make sure conf directory exists
  file: dest="{{logstash_etc_dir}}" state=directory owner="{{logstash_user}}" group="{{logstash_group}}"
  notify: restart_logstash

- name: make sure log directory exists
  file: dest="{{logstash_log_dir}}" state=directory owner="{{logstash_user}}" group="{{logstash_group}}"
  notify: restart_logstash

- name: Conf logstashInput
  template: src=logstash_input.conf.j2 dest="{{logstash_etc_dir}}/logstash_input.conf"
  notify: restart_logstash
  
- name: Conf logstashOutput
  template: src=logstash_output.conf.j2 dest="{{logstash_etc_dir}}/logstash_output.conf"
  notify: restart_logstash

- name: Conf logstashFilter
  template: src=logstash_filter.conf.j2 dest="{{logstash_etc_dir}}/logstash_filter.conf"
  notify: restart_logstash


- name: configure /etc/default/logstash
  template: src=etc_default_logstash.j2 dest=/etc/default/logstash
  notify: restart_logstash  

- name: symlink conf.d
  file: src="{{logstash_etc_dir}}" dest=/etc/logstash/conf.d state=link owner="{{logstash_user}}" group="{{logstash_group}}" force=true
  notify: restart_logstash  
